.TH tcprules-smtp 8
.SH NAME
tcprules-smtp \- short for
  '/usr/local/bin/tcprules /etc/qmail/tcp.smtp.cdb \\
    /etc/qmail/tcp.smtp.tmp < /etc/qmail/tcp.smtp'
.SH SYNOPSIS
.B tcprules-smtp
.SH DESCRIPTION
.B tcprules-smtp
runs
  '/usr/local/bin/tcprules /etc/qmail/tcp.smtp.cdb \\
    /etc/qmail/tcp.smtp.tmp < /etc/qmail/tcp.smtp'.
.SH FILES
/etc/qmail/tcp.smtp,
/etc/qmail/tcp.smtp.cdb
.SH SEE ALSO
tcprules(1),
tcpserver(1),
qmail-smtpd(8)
