#!/bin/sh

# Using stdout for logging
# Using control/defaultdelivery from qmail-local to deliver messages by default

exec env - PATH="/var/lib/qmail/bin:$PATH" \
qmail-start "`cat /var/lib/qmail/control/defaultdelivery`"
