#!/bin/sh

QMAILDUID=`/usr/bin/id -u qmaild`
NOFILESGID=`/usr/bin/id -g qmaild`
exec /usr/bin/softlimit -m 2000000 \
	/usr/bin/tcpserver -v -p -x /etc/qmail/tcp.smtp.cdb \
	-u $QMAILDUID -g $NOFILESGID 0 smtp /var/qmail/bin/qmail-smtpd 2>&1
