#! /bin/sh
#
# skeleton	example file to build /etc/init.d/ scripts.
#		This file should be used to construct scripts for /etc/init.d.
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian GNU/Linux
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.8  03-Mar-1998  miquels@cistron.nl
#
# This file was automatically customized by dh-make on Thu, 13 Apr 2000 09:41:23 +0200

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC=qmail

SERVICE="qmail-start qmail-smtpd"

set -e

case "$1" in
  start)
	echo -n "Starting $DESC:"
	for i in ${SERVICE}; do
		ln -fs /var/supervise/qmail/$i /var/service
		echo -n " $i"
	done
	echo "."
	;;
  stop)
	echo -n "Stopping $DESC:"
	for i in ${SERVICE}; do
		rm -f /var/service/$i
		svc -dx /var/supervise/qmail/$i
		echo -n " $i"
		if [ -d /var/supervise/qmail/${i}/log ]; then
			svc -dx /var/supervise/qmail/${i}/log
			echo -n " $i/log"
		fi
	done
	echo "."
	;;
  reload)
	#
	#	If the daemon can reload its config files on the fly
	#	for example by sending it SIGHUP, do it here.
	#
	#	If the daemon responds to changes in its config file
	#	directly anyway, make this a do-nothing entry.
	#
	echo "Reloading $DESC configuration files (sending HUP):"
	for i in ${SERVICE}; do
		svc -h /var/service/$i
		echo -n " $i"
	done
	echo "."
  ;;
  restart|force-reload)
	#
	#	If the "reload" option is implemented, move the "force-reload"
	#	option to the "reload" entry above. If not, "force-reload" is
	#	just the same as "restart".
	#
	echo -n "Restarting $DESC:"
	for i in ${SERVICE}; do
		svc -t /var/service/$i
		echo -n " $i"
	done
	echo "."
	;;
  cdb)
	tcprules /etc/qmail/tcp.smtp.cdb /etc/qmail/tcp.smtp.tmp \
		< /etc/qmail/tcp.smtp
	chmod 644 /etc/qmail/tcp.smtp*
	echo "/etc/qmail/tcp.smtp reloaded."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|reload|force-reload|cdb}" >&2
	exit 1
	;;
esac

exit 0
